### ISSUE TITLE
I want to modify the rpc of storage-node. What should I do? 

### ISSUE THREAD

**Issue by qq1739920004** [hubofvalley/Testnet-Guides#1]
I want to modify the rpc of storage-node. What should I do?

**Comment by hubofvalley** [comment]
re-enter the json-rpc
```
read -p "Enter json-rpc: " BLOCKCHAIN_RPC_ENDPOINT && echo "Current json-rpc: $BLOCKCHAIN_RPC_ENDPOINT"

echo "export BLOCKCHAIN_RPC_ENDPOINT=\"$BLOCKCHAIN_RPC_ENDPOINT\"" >> ~/.bash_profile
source ~/.bash_profile

sed -i '
s|^\s*#\?\s*blockchain_rpc_endpoint\s*=.*|blockchain_rpc_endpoint = "'"$BLOCKCHAIN_RPC_ENDPOINT"'"|
' $HOME/0g-storage-node/run/config-testnet.toml
```

**Comment by qq1739920004** [comment]
> re-enter the json-rpc
> 
> ```
> read -p "Enter json-rpc: " BLOCKCHAIN_RPC_ENDPOINT && echo "Current json-rpc: $BLOCKCHAIN_RPC_ENDPOINT"
> 
> echo "export BLOCKCHAIN_RPC_ENDPOINT=\"$BLOCKCHAIN_RPC_ENDPOINT\"" >> ~/.bash_profile
> source ~/.bash_profile
> 
> sed -i '
> s|^\s*#\?\s*blockchain_rpc_endpoint\s*=.*|blockchain_rpc_endpoint = "'"$BLOCKCHAIN_RPC_ENDPOINT"'"|
> ' $HOME/0g-storage-node/run/config-testnet.toml
> ```

I forgot the source ~/.bash profile, thank you
